/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bot;

import java.util.Optional;
import java.util.Random;
import java.util.Vector;

import org.jsoup.nodes.Element;

import com.pengrad.telegrambot.TelegramBot;
import com.pengrad.telegrambot.UpdatesListener;
import com.pengrad.telegrambot.model.Update;
import com.pengrad.telegrambot.request.SendMessage;
import com.pengrad.telegrambot.response.SendResponse;

// import com.openhtmltopdf.pdfboxout.PdfRendererBuilder;

import bot.LKParser;
import bot.User;

public class App {
    private static String key = "5803293395:AAFPAXk98c3yzWWpKEuFYP2lE4G8l1MHNjE";
    private static Vector<User> users = new Vector<>();
    private static Vector<Long> whantTickTackToe = new Vector<>();

    public static void main(String[] args) {
        System.out.println("Connecting bot...");
        TelegramBot bot = new TelegramBot(App.key);

        System.out.println("Starting...");
        bot.setUpdatesListener(updates -> {
            for (Update update : updates) {
                System.out.println("Recived: " + update.message().from().firstName());
                String executeMessage = "Я не знаю такой команды..., воспользуйся командой /help";
                String[] attempt = update.message().text().split(" ");
                long chatId = update.message().chat().id();

                
                switch (attempt[0].toUpperCase()) {
                    case "/LOGIN": {
                        if (!(User.getUserByChatId(chatId, users) == null)) {
                            executeMessage = "Вы уже вошли!";
                            break;
                        }

                        if (attempt.length != 3) {
                            executeMessage = "Пришли мне логин и пароль вот в таком формате: /login login password";
                            break;
                        }

                        executeMessage = "Обрабатываю запрос...";
                        SendResponse message = bot.execute(new SendMessage(chatId, executeMessage));

                        if (!LKParser.loginIn(attempt[1], attempt[2])) {
                            executeMessage = "Что-то пошло не так...";
                            break;
                        }

                        users.add(new User(attempt[1], attempt[2], chatId));

                        executeMessage = "Успешно!";
                        break;
                    } 

                    case "/START": {
                        executeMessage =  "Привет, студент 👋!\n"
                                        + "Я - бот помощник, моя задача получить доступ к ЛК и сохранять для тебя самое важное.\n"
                                        + "Что Я могу получить?\n"
                                        + "1. Расписание\n"
                                        + "2. Все твои задания\n"
                                        + "3. Материалы к ЛК\n"
                                        + "\n"
                                        + "Чтобы начать, введи команду /login \"логин\" \"пароль\" чтобы начать!"
                                        + "\n"
                                        + "Другие команды:\n"
                                        + "1. /tic_tac: Игра в камень ножницы бумага с сулчайным человеком\n"
                                        + "2. /m \"имя пользователя\": ответить пользователю из ЛК\n"
                                        + "3. /timetable: Получить полностью своё расписание\n"
                                        + "4. /task \"имя предмета\": Получить все материалы за промежуток времени\n";
                        break;
                    }
                    
                    case "/HELP": {
                        executeMessage =  "Привет, студент 👋!\n"
                                        + "Я - бот помощник, моя задача получить доступ к ЛК и сохранять для тебя самое важное.\n"
                                        + "Что Я могу получить?\n"
                                        + "1. Расписание\n"
                                        + "2. Все твои задания\n"
                                        + "3. Материалы к ЛК\n"
                                        + "\n"
                                        + "Чтобы начать, введи команду /login \"логин\" \"пароль\" чтобы начать!"
                                        + "\n"
                                        + "Другие команды:\n"
                                        + "1. /tic_tac: Игра в камень ножницы бумага с сулчайным человеком\n"
                                        + "2. /m \"имя пользователя\": ответить пользователю из ЛК\n"
                                        + "3. /timetable: Получить полностью своё расписание\n"
                                        + "4. /task \"имя предмета\": Получить все материалы за промежуток времени\n";
                        break;
                    }

                    case "/TIC_TAC": {
                        if (whantTickTackToe.size() < 2) {
                            executeMessage = "Ждём другого игрока!";
                            if (!whantTickTackToe.contains(chatId)) {
                                whantTickTackToe.add(chatId);
                            }
                            break;
                        }
                        int player_1 = new Random().ints(0, 3)
                                                    .findFirst()
                                                    .getAsInt();
                        int player_2 = new Random().ints(0, 3)
                                                    .findFirst()
                                                    .getAsInt();
                        Long opponentId = whantTickTackToe.get(
                            new Random().ints(0, whantTickTackToe.size())
                                        .findFirst()
                                        .getAsInt()
                        );

                        if (player_1 > player_2) {
                            bot.execute(new SendMessage(chatId, "Вы выйграли!"));
                            bot.execute(new SendMessage(opponentId, "Вы проиграли!"));
                        } else if (player_1 < player_2) {
                            bot.execute(new SendMessage(opponentId, "Вы выйграли!"));
                            bot.execute(new SendMessage(chatId, "Вы проиграли!"));
                        } else {
                            bot.execute(new SendMessage(chatId, "Ничья!"));
                            bot.execute(new SendMessage(opponentId, "Ничья!"));
                        }
                        
                        executeMessage = "Сыграть ещё раз: /tic_tac";
                        break;
                    }

                    case "/LOGOUT": {
                        if (User.getUserByChatId(chatId, users) == null) {
                            executeMessage = "Вы ещё не вошли!";
                            break;
                        }

                        users.removeIf(n -> (n.getTelegramChatID() == chatId));
                        executeMessage = "Сделано!";
                        break;
                    }

                    case "/TIMETABLE": {
                        User user = User.getUserByChatId(chatId, users);
                        
                        if (user == null) {
                            executeMessage = "Вы ещё не вошли!";
                            break;
                        }

                        Optional<Element> timetable = LKParser.getTimetable(user.getLogin(), user.getPassword());

                        if (timetable.isEmpty()) {
                            executeMessage = "Что-то пошло не так... Возможно ЛК не работет";
                            break;
                        }

                        //TODO: This part of code is not working? What is happening with gradle?
                        /*
                        try (OutputStream os = new FileOutputStream("/Users/me/Documents/pdf/out.pdf")) {
                            PdfRendererBuilder builder = new PdfRendererBuilder();
                            builder.useFastMode();
                            builder.withUri("file:///Users/me/Documents/pdf/in.htm");
                            builder.toStream(os);
                            builder.run();
                        }
                        */

                        executeMessage = "Произошла внутреняя ошибка! PdfRendereBuild не установлен!";
                        break;
                    }

                    case "/M": {
                        User user = User.getUserByChatId(chatId, users);
                        
                        if (user == null) {
                            executeMessage = "Вы ещё не вошли!";
                            break;
                        }

                        executeMessage = "Простите, но мы ещё не успели это реализовать 😖";
                        break;
                    }
                }

                SendResponse response = bot.execute(new SendMessage(chatId, executeMessage));
            }
            return UpdatesListener.CONFIRMED_UPDATES_ALL;
        });
    }
}
